USE [WebDB3]
GO
INSERT INTO dbo.Catalog([CatalogID],[Name])
	VALUES(1,N'Máy ảnh Canon')
INSERT INTO dbo.Catalog([CatalogID],[Name])
	VALUES(2,N'Máy ảnh Sony')
INSERT INTO dbo.Catalog([CatalogID],[Name])
	VALUES(3,N'Máy ảnh Nikon')
INSERT INTO dbo.Catalog([CatalogID],[Name])
	VALUES(4,N'Máy ảnh Fujifilm')
INSERT INTO dbo.Catalog([CatalogID],[Name])
	VALUES(5,N'Máy ảnh khác')
INSERT INTO dbo.Catalog([CatalogID],[Name])
	VALUES(6,N'Ống kính - Flash')
INSERT INTO dbo.Catalog([CatalogID],[Name])
	VALUES(7,N'Phụ kiện')
INSERT INTO dbo.Catalog([CatalogID],[Name])
	VALUES(8,N'Gopro')